---
- name: Check for /etc/rhosp-release
  stat:
      path: "/etc/rhosp-release"
  register: rhosp_release_file

- name: Get /etc/rhosp-release content
  command: cat /etc/rhosp-release
  register: rhosp_release_content
  when: rhosp_release_file.stat.exists

- name: Set overcloud_version from /etc/rhosp-release output
  set_fact:
      undercloud_version: "{{ rhosp_release_content.stdout | regex_replace('^Red Hat OpenStack Platform release ([0-9]+\\.\\d+).*', '\\1') }}"
      overcloud_version: "{{ rhosp_release_content.stdout | regex_replace('^Red Hat OpenStack Platform release ([0-9]+\\.\\d+).*', '\\1') }}"
  when: rhosp_release_file.stat.exists

- name: Set version back to integer for versions x.0 for backward compatibility
  set_fact:
    undercloud_version: "{{ version_value|int }}"
    overcloud_version: "{{ version_value|int }}"
  vars:
      version_value: "{{ undercloud_version }}"
  when:
    - undercloud_version is defined
    - undercloud_version.split('.')[1] is defined
    - undercloud_version.split('.')[1] == "0"
